services:
  storage:
    image: storage:latest
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=testuser
      - DB_PASSWORD=testpass
      - DB_NAME=testdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    networks:
      - testnetwork

  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    volumes: []
    networks:
      - testnetwork
    command: postgres -c 'max_connections=300' -c 'shared_buffers=2GB' -c 'work_mem=32MB' -c 'maintenance_work_mem=256MB' -c 'effective_cache_size=6GB' -c 'checkpoint_timeout=15min' -c 'checkpoint_completion_target=0.9' -c 'wal_buffers=16MB' -c 'synchronous_commit=off'

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes: []
    networks:
      - testnetwork

  pgbench:
    image: postgres:16
    entrypoint: ["tail", "-f", "/dev/null"]
    depends_on:
      - db
    networks:
      - testnetwork

  pgbouncer:
    image: edoburu/pgbouncer
    ports:
      - "6432:6432"
    environment:
      - DB_USER=testuser
      - DB_PASSWORD=testpass
      - DB_NAME=testdb
      - DB_HOST=db
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
    networks:
      - testnetwork

networks:
  testnetwork:
    driver: bridge

volumes:
  pgdata:
