services:
  storage:
    image: storage:latest
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=adminpass
      - DB_NAME=filestore
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: filestore
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
